import { StyleSheet, Platform, StatusBar } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F5EF', paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0 },
  headerBannerContainer: { width: '100%', height: 110, backgroundColor: '#12352A', justifyContent: 'center', alignItems: 'center' },
  headerImageBanner: { width: '100%', height: '100%' },
  menuBar: { backgroundColor: '#12352A', paddingVertical: 10, paddingHorizontal: 15, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: 3, borderBottomColor: '#C5A059' },
  menuBarButton: { padding: 4 },
  menuBarText: { color: '#C5A059', fontSize: 16, fontWeight: '900', letterSpacing: 1 },
  refreshBarButton: { backgroundColor: '#C5A059', paddingVertical: 5, paddingHorizontal: 10, borderRadius: 6 },
  refreshBarText: { color: '#111111', fontSize: 11, fontWeight: 'bold' },
  menuOverlay: { position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', backgroundColor: 'rgba(0,0,0,0.4)', zIndex: 9 },
  sideMenu: { backgroundColor: '#0B221B', position: 'absolute', top: 0, left: 0, width: 260, height: '100%', zIndex: 10, padding: 20, paddingTop: 50, elevation: 10, borderRightWidth: 1, borderRightColor: '#C5A059' },
  profileHeader: { alignItems: 'center', marginBottom: 20 },
  profileImage: { width: 70, height: 70, borderRadius: 35, backgroundColor: '#FFFFFF', marginBottom: 8, borderWidth: 2, borderColor: '#C5A059' },
  profileName: { color: '#FFFFFF', fontSize: 16, fontWeight: 'bold', textAlign: 'center', letterSpacing: 1 },
  editProfileMenuBtn: { backgroundColor: '#12352A', paddingVertical: 5, paddingHorizontal: 10, borderRadius: 5, marginTop: 5, borderWidth: 1, borderColor: '#C5A059' },
  editProfileMenuText: { color: '#C5A059', fontSize: 11, fontWeight: 'bold' },
  adminMenuBtn: { backgroundColor: '#C5A059', padding: 10, borderRadius: 8, alignItems: 'center', marginTop: 10 },
  adminMenuText: { color: '#111111', fontSize: 13, fontWeight: 'bold' },
  menuItem: { paddingVertical: 14 },
  menuItemText: { color: '#FFFFFF', fontSize: 15, fontWeight: 'bold', letterSpacing: 1 },
  menuDivider: { height: 1, backgroundColor: '#1B4D3E', marginVertical: 15 },
  loginButtonMenu: { backgroundColor: '#FFFFFF', padding: 12, borderRadius: 8, alignItems: 'center' },
  loginButtonMenuText: { color: '#12352A', fontSize: 15, fontWeight: 'bold' },
  feedContainer: { padding: 15, paddingBottom: 50 },
  sectionTitle: { fontSize: 18, fontWeight: '800', color: '#12352A', marginTop: 10, marginBottom: 15, textTransform: 'uppercase', letterSpacing: 1 },
  homeLeaderboardCard: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 15, marginBottom: 20, elevation: 3, borderWidth: 1, borderColor: '#E5E5DF' },
  homeLbRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#F0F0EA' },
  matchCardWidget: { backgroundColor: '#FFFFFF', borderRadius: 12, marginBottom: 20, borderWidth: 1, borderColor: '#C5A059', overflow: 'hidden', elevation: 3 },
  matchWidgetTopBar: { backgroundColor: '#12352A', paddingVertical: 8, paddingHorizontal: 15, alignItems: 'center' },
  matchWidgetHeader: { color: '#C5A059', fontSize: 13, fontWeight: '900', letterSpacing: 1.5 },
  matchWidgetBody: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 15 },
  matchTeamColumn: { alignItems: 'center', flex: 1 },
  matchTeamLogo: { width: 50, height: 50, marginBottom: 6 },
  matchTeamName: { fontWeight: 'bold', fontSize: 13, color: '#111', textAlign: 'center' },
  matchInfoColumn: { alignItems: 'center', paddingHorizontal: 10 },
  vsText: { fontSize: 16, fontWeight: '900', color: '#C5A059', marginBottom: 4 },
  matchDateBadge: { fontSize: 11, fontWeight: 'bold', color: '#12352A', backgroundColor: '#F0F0EA', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 4, marginBottom: 4, textAlign: 'center' },
  matchTournamentBadge: { fontSize: 10, color: '#12352A', fontWeight: '900', textTransform: 'uppercase', marginBottom: 2, textAlign: 'center' },
  matchStadiumText: { fontSize: 10, color: '#666', textAlign: 'center' },
  rssCard: { backgroundColor: '#FFFFFF', padding: 12, borderRadius: 8, marginBottom: 10, borderWidth: 1, borderColor: '#E5E5DF' },
  rssTitle: { fontWeight: 'bold', fontSize: 14, color: '#12352A', marginBottom: 4 },
  rssDate: { fontSize: 11, color: '#666' },
  newsCard: { backgroundColor: '#FFFFFF', borderRadius: 12, overflow: 'hidden', marginBottom: 15, elevation: 3, borderWidth: 1, borderColor: '#E5E5DF' },
  newsImage: { width: '100%', height: 150 },
  newsTextContainer: { padding: 15 },
  newsTitle: { fontSize: 17, fontWeight: '700', color: '#111111', marginBottom: 5 },
  newsDate: { fontSize: 12, color: '#12352A', fontWeight: 'bold' },
  roundSelectorRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#FFFFFF', padding: 12, borderRadius: 10, marginBottom: 15, borderWidth: 1, borderColor: '#C5A059' },
  currentRoundText: { fontSize: 16, fontWeight: '900', color: '#12352A', textTransform: 'uppercase' },
  matchCard: { backgroundColor: '#FFFFFF', borderRadius: 10, padding: 12, marginBottom: 12, borderWidth: 1, borderColor: '#E5E5DF' },
  matchRoundText: { fontSize: 11, color: '#666', fontWeight: 'bold' },
  matchTeamsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  teamBadgeWithLogo: { flex: 1, paddingVertical: 12, paddingHorizontal: 6, borderRadius: 8, justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
  darkOverlay: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.5)', borderRadius: 8 },
  teamBadgeText: { fontWeight: '900', fontSize: 14, flexShrink: 1, zIndex: 2, textAlign: 'center' },
  scoreInput: { width: 45, height: 45, backgroundColor: '#F5F5EF', textAlign: 'center', borderRadius: 8, fontSize: 18, fontWeight: 'bold', borderWidth: 1, borderColor: '#C5A059', color: '#111', marginHorizontal: 4, padding: 0 },
  lbRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', padding: 10, borderRadius: 8, marginBottom: 6, borderWidth: 1, borderColor: '#E5E5DF' },
  myLbRow: { backgroundColor: '#12352A', borderWidth: 1, borderColor: '#C5A059' },
  lbRank: { width: 30, fontWeight: 'bold', fontSize: 15, textAlign: 'center', color: '#C5A059' },
  lbAvatar: { width: 30, height: 30, borderRadius: 15, marginRight: 10, borderWidth: 1, borderColor: '#C5A059' },
  detailContainer: { padding: 15, backgroundColor: '#F5F5EF', flexGrow: 1 },
  detailCard: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 15, elevation: 3, marginTop: 10, borderWidth: 1, borderColor: '#E5E5DF' },
  detailImage: { width: '100%', height: 200, borderRadius: 8, marginBottom: 15 },
  detailTitle: { fontSize: 20, fontWeight: '900', color: '#12352A', marginBottom: 10 },
  detailDate: { fontSize: 12, color: '#666', marginBottom: 15 },
  detailBody: { fontSize: 15, color: '#333', lineHeight: 22 },
  commentRow: { backgroundColor: '#FFFFFF', padding: 12, borderRadius: 8, flexDirection: 'row', alignItems: 'center', marginBottom: 10, borderWidth: 1, borderColor: '#E5E5DF' },
  commentAvatar: { width: 32, height: 32, borderRadius: 16, marginRight: 10, borderWidth: 1, borderColor: '#C5A059' },
  commentUser: { fontWeight: 'bold', fontSize: 12, color: '#12352A', marginBottom: 2 },
  commentText: { fontSize: 13, color: '#111111' },
  commentInputContainer: { flexDirection: 'row', marginTop: 10, alignItems: 'center' },
  commentInput: { flex: 1, backgroundColor: '#FFFFFF', padding: 12, borderRadius: 8, borderWidth: 1, borderColor: '#C5A059', fontSize: 14, color: '#111' },
  commentSendBtn: { backgroundColor: '#12352A', paddingVertical: 12, paddingHorizontal: 15, borderRadius: 8, marginLeft: 8 },
  loginScreenContainer: { flexGrow: 1, padding: 20, justifyContent: 'center', backgroundColor: '#F5F5EF' },
  backButton: { marginBottom: 20, marginTop: 30 },
  backButtonText: { color: '#12352A', fontSize: 14, fontWeight: 'bold' },
  loginHeader: { fontSize: 24, fontWeight: '900', color: '#12352A', marginBottom: 15 },
  loginSubheader: { fontSize: 14, color: '#555', marginBottom: 20 },
  inputField: { backgroundColor: '#FFFFFF', padding: 15, borderRadius: 8, fontSize: 15, marginBottom: 15, borderWidth: 1, borderColor: '#C5A059', color: '#111' },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 15 },
  checkboxBox: { width: 20, height: 20, borderRadius: 4, borderWidth: 1, borderColor: '#C5A059', backgroundColor: '#FFFFFF', justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  checkboxChecked: { backgroundColor: '#12352A' },
  checkboxLabel: { fontSize: 14, color: '#12352A', fontWeight: '600' },
  primaryButton: { backgroundColor: '#12352A', padding: 15, borderRadius: 8, alignItems: 'center', marginTop: 5, borderWidth: 1, borderColor: '#C5A059' },
  primaryButtonText: { color: '#FFFFFF', fontSize: 14, fontWeight: 'bold', letterSpacing: 1 },
  googleButton: { backgroundColor: '#4285F4', padding: 15, borderRadius: 8, alignItems: 'center', marginTop: 10 },
  googleButtonText: { color: '#FFFFFF', fontSize: 13, fontWeight: 'bold' },
  secondaryButton: { padding: 12, alignItems: 'center', marginTop: 10 },
  secondaryButtonText: { color: '#12352A', fontSize: 13, fontWeight: '600' },
  adminNewsRow: { backgroundColor: '#FFFFFF', padding: 12, borderRadius: 8, flexDirection: 'row', alignItems: 'center', marginBottom: 8, borderWidth: 1, borderColor: '#E5E5DF' },
  adminUserRow: { backgroundColor: '#FFFFFF', padding: 12, borderRadius: 8, flexDirection: 'row', alignItems: 'center', marginBottom: 8, borderWidth: 1, borderColor: '#E5E5DF' },
  deleteBtn: { paddingVertical: 6, paddingHorizontal: 10, borderRadius: 6, backgroundColor: '#8A1C1C' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center', padding: 20 },
  modalContainer: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 20, width: '100%', maxWidth: 400, borderWidth: 2, borderColor: '#C5A059', alignItems: 'center' },
  modalHeader: { fontSize: 16, fontWeight: '900', color: '#12352A', marginBottom: 15 },
  splashContainer: { flex: 1, backgroundColor: '#000000', justifyContent: 'center', alignItems: 'center', width: '100%', height: '100%' },
  splashVideoWrapper: { width: '80%', height: '50%', justifyContent: 'center', alignItems: 'center' },
  splashVideo: { width: '100%', height: '100%', borderRadius: 12 }
});
